<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-RenovatorApp.API-e8c407c0-192a-4bcc-bac6-0f98cfca5677</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" Version="12.5.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" NoWarn="NU1605"/>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.0" NoWarn="NU1605"/>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.0"/>
        <PackageReference Include="Microsoft.Identity.Web" Version="3.0.0"/>
        <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.0.0"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.4.13" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Auth\RenovatorApp.Auth\RenovatorApp.Auth.csproj" />
      <ProjectReference Include="..\RenovatorApp.Application\RenovatorApp.Application.csproj" />
    </ItemGroup>

</Project>
